from PyQt5 import QtCore, QtWidgets  


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 678)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.read_excel_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.read_excel_label_2.setGeometry(QtCore.QRect(25, 0, 145, 109))
        self.read_excel_label_2.setObjectName("read_excel_label_2")
        self.file_path_edt_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.file_path_edt_2.setGeometry(QtCore.QRect(177, 44, 136, 21))
        self.file_path_edt_2.setObjectName("file_path_edt_2")
        self.choice_bt_2 = QtWidgets.QPushButton(self.centralwidget)
        self.choice_bt_2.setGeometry(QtCore.QRect(320, 40, 105, 30))
        self.choice_bt_2.setObjectName("choice_bt_2")
        self.checkBox_open_mean_3 = QtWidgets.QPushButton(self.centralwidget)#后期将checkbox改成pushbutton
        self.checkBox_open_mean_3.setGeometry(QtCore.QRect(380, 300, 320, 30))
        self.checkBox_open_mean_3.setObjectName("checkBox_open_mean_3")
        self.choice_pic_type_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.choice_pic_type_label_3.setGeometry(QtCore.QRect(380, 220, 261, 51))
        self.choice_pic_type_label_3.setObjectName("choice_pic_type_label_3")
        self.checkBox_all_hi_price_3 = QtWidgets.QPushButton(self.centralwidget)
        self.checkBox_all_hi_price_3.setGeometry(QtCore.QRect(380, 260, 320, 30))
        self.checkBox_all_hi_price_3.setObjectName("checkBox_all_hi_price_3")
        self.picture_type_label = QtWidgets.QLabel(self.centralwidget)
        self.picture_type_label.setGeometry(QtCore.QRect(10, 220, 261, 21))
        self.picture_type_label.setObjectName("picture_type_label")
        self.stock_read_lineedt = QtWidgets.QLineEdit(self.centralwidget)
        self.stock_read_lineedt.setGeometry(QtCore.QRect(20, 110, 359, 21))
        self.stock_read_lineedt.setText("")
        self.stock_read_lineedt.setObjectName("stock_read_lineedt")
        self.stock_read_label = QtWidgets.QLabel(self.centralwidget)
        self.stock_read_label.setGeometry(QtCore.QRect(20, 60, 359, 51))
        self.stock_read_label.setObjectName("stock_read_label")
        self.checkBox_ma = QtWidgets.QPushButton(self.centralwidget)#
        self.checkBox_ma.setGeometry(QtCore.QRect(20, 250, 320, 30))
        self.checkBox_ma.setObjectName("checkBox_ma")
        self.checkBox_kline = QtWidgets.QPushButton(self.centralwidget)#
        self.checkBox_kline.setGeometry(QtCore.QRect(20, 280, 320, 30))
        self.checkBox_kline.setObjectName("checkBox_kline")
        self.checkBox_price_upandown = QtWidgets.QPushButton(self.centralwidget)
        self.checkBox_price_upandown.setGeometry(QtCore.QRect(20, 310, 320, 30))
        self.checkBox_price_upandown.setObjectName("checkBox_price_upandown")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(440, 10, 300, 150))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        
        self.read_excel_label_2.setText(_translate("MainWindow", "Excel文件读取路径："))
        self.choice_bt_2.setText(_translate("MainWindow", "选择文件预览"))
        self.checkBox_open_mean_3.setText(_translate("MainWindow", "开盘价均值柱状图"))
        self.choice_pic_type_label_3.setText(_translate("MainWindow", "选择想要查看到数据图片类型："))
        self.checkBox_all_hi_price_3.setText(_translate("MainWindow", "每支股票达到的最高价的柱状图"))
        self.picture_type_label.setText(_translate("MainWindow", "选择你想要查看的该股票数据图类型："))
        self.stock_read_label.setText(_translate("MainWindow", "输入你想要查看的股票代号（1001~1100）："))
        self.checkBox_ma.setText(_translate("MainWindow", "移动平均线图"))
        self.checkBox_kline.setText(_translate("MainWindow", "K线图"))
        self.checkBox_price_upandown.setText(_translate("MainWindow", "价格走势折线图"))